from __future__ import annotations

import json
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path


LOCAL_COMPOSE_FILE = "docker-compose.naval-local.yml"
LOCAL_ENV_FILE = ".env.naval-local"
AWS_TERRAFORM_DIR = Path("infra") / "naval-bootstrap" / "aws"
AWS_ENV_FILE = ".env.naval-aws"

LOCAL_COMPOSE_TEMPLATE = """version: "3.9"
services:
  temporal:
    image: temporalio/auto-setup:1.25.2
    environment:
      - DB=sqlite
      - DB_FILENAME=/etc/temporal/temporal.db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    ports:
      - "7233:7233"
      - "8233:8233"

  localstack:
    image: localstack/localstack:3.0
    environment:
      - SERVICES=s3,sqs,dynamodb,sts
      - DEBUG=0
      - AWS_DEFAULT_REGION=ap-northeast-1
    ports:
      - "4566:4566"
"""

LOCAL_ENV_TEMPLATE = """# Local bootstrap environment
FLEET_REGION=ap-northeast-1
FLEET_SQS_NAME=naval-local-queue
FLEET_STATE_TABLE=naval-local-state
FLEET_BUDGET_TABLE=naval-local-budget
NAVAL_BUDGET_GUARD_TABLE=naval-local-budget-guard
NAVAL_INDEX_TABLE=naval-local-index
FLEET_S3_BUCKET=naval-local-artifacts
TEMPORAL_ADDRESS=localhost:7233
TEMPORAL_NAMESPACE=default
TEMPORAL_TASK_QUEUE=naval-mission
"""

AWS_MAIN_TF = """terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

locals {
  sqs_name              = "${var.name_prefix}-queue"
  state_table_name      = "${var.name_prefix}-state"
  budget_table_name     = "${var.name_prefix}-budget"
  budget_guard_name     = "${var.name_prefix}-budget-guard"
  index_table_name      = "${var.name_prefix}-index"
  artifact_bucket_name  = "${var.name_prefix}-artifacts"
}

resource "aws_sqs_queue" "fleet_queue" {
  name = local.sqs_name
}

resource "aws_dynamodb_table" "state" {
  name         = local.state_table_name
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "mission_id"
  range_key    = "task_id"

  attribute {
    name = "mission_id"
    type = "S"
  }

  attribute {
    name = "task_id"
    type = "S"
  }
}

resource "aws_dynamodb_table" "budget" {
  name         = local.budget_table_name
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "mission_id"

  attribute {
    name = "mission_id"
    type = "S"
  }
}

resource "aws_dynamodb_table" "budget_guard" {
  name         = local.budget_guard_name
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "mission_id"

  attribute {
    name = "mission_id"
    type = "S"
  }
}

resource "aws_dynamodb_table" "index" {
  name         = local.index_table_name
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "mission_id"
  range_key    = "task_id"

  attribute {
    name = "mission_id"
    type = "S"
  }

  attribute {
    name = "task_id"
    type = "S"
  }
}

resource "aws_s3_bucket" "artifacts" {
  bucket        = local.artifact_bucket_name
  force_destroy = var.force_destroy
}
"""

AWS_VARIABLES_TF = """variable "region" {
  description = "AWS region"
  type        = string
  default     = "ap-northeast-1"
}

variable "name_prefix" {
  description = "Resource name prefix (lowercase letters, digits, hyphen)"
  type        = string
  default     = "naval-vnext"
}

variable "force_destroy" {
  description = "Allow deleting non-empty S3 bucket on destroy"
  type        = bool
  default     = false
}
"""

AWS_OUTPUTS_TF = """output "region" {
  value = var.region
}

output "sqs_name" {
  value = aws_sqs_queue.fleet_queue.name
}

output "state_table" {
  value = aws_dynamodb_table.state.name
}

output "budget_table" {
  value = aws_dynamodb_table.budget.name
}

output "budget_guard_table" {
  value = aws_dynamodb_table.budget_guard.name
}

output "index_table" {
  value = aws_dynamodb_table.index.name
}

output "artifact_bucket" {
  value = aws_s3_bucket.artifacts.bucket
}
"""

AWS_TFVARS_EXAMPLE = """region       = "ap-northeast-1"
name_prefix  = "naval-vnext"
force_destroy = false
"""

AWS_README = """# Naval AWS Bootstrap (Terraform)

Generated by `python -m naval up --profile aws`.

## Commands

```
terraform -chdir=. init
terraform -chdir=. apply -auto-approve -var=region=ap-northeast-1 -var=name_prefix=naval-vnext
terraform -chdir=. destroy -auto-approve -var=region=ap-northeast-1 -var=name_prefix=naval-vnext
```
"""


@dataclass
class LocalBootstrapResult:
    compose_file: Path
    env_file: Path
    created_files: list[Path]
    started: bool
    message: str


@dataclass
class AwsBootstrapResult:
    terraform_dir: Path
    env_file: Path
    created_files: list[Path]
    applied: bool
    message: str


def ensure_local_bootstrap_files(repo_root: Path) -> tuple[Path, Path, list[Path]]:
    compose_file = repo_root / LOCAL_COMPOSE_FILE
    env_file = repo_root / LOCAL_ENV_FILE
    created: list[Path] = []
    if not compose_file.exists():
        compose_file.write_text(LOCAL_COMPOSE_TEMPLATE, encoding="utf-8")
        created.append(compose_file)
    if not env_file.exists():
        env_file.write_text(LOCAL_ENV_TEMPLATE, encoding="utf-8")
        created.append(env_file)
    return compose_file, env_file, created


def _write_if_missing(path: Path, content: str, created: list[Path]) -> None:
    if path.exists():
        return
    path.write_text(content, encoding="utf-8")
    created.append(path)


def _sanitize_name_prefix(value: str) -> str:
    normalized = value.strip().lower()
    normalized = re.sub(r"[^a-z0-9-]+", "-", normalized)
    normalized = re.sub(r"-{2,}", "-", normalized).strip("-")
    if not normalized:
        normalized = "naval-vnext"
    return normalized[:40]


def ensure_aws_bootstrap_files(repo_root: Path) -> tuple[Path, list[Path]]:
    tf_dir = repo_root / AWS_TERRAFORM_DIR
    tf_dir.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []
    _write_if_missing(tf_dir / "main.tf", AWS_MAIN_TF, created)
    _write_if_missing(tf_dir / "variables.tf", AWS_VARIABLES_TF, created)
    _write_if_missing(tf_dir / "outputs.tf", AWS_OUTPUTS_TF, created)
    _write_if_missing(tf_dir / "terraform.tfvars.example", AWS_TFVARS_EXAMPLE, created)
    _write_if_missing(tf_dir / "README.md", AWS_README, created)
    return tf_dir, created


def _terraform_output_json(repo_root: Path, tf_dir: Path) -> dict:
    cmd = ["terraform", "-chdir", str(tf_dir), "output", "-json"]
    proc = subprocess.run(cmd, cwd=str(repo_root), capture_output=True, text=True)
    if proc.returncode != 0:
        return {}
    try:
        return json.loads(proc.stdout)
    except Exception:
        return {}


def _write_aws_env_file(repo_root: Path, outputs: dict) -> Path:
    env_file = repo_root / AWS_ENV_FILE
    def _v(name: str, default: str = "") -> str:
        raw = outputs.get(name, {})
        if isinstance(raw, dict):
            return str(raw.get("value", default))
        return default

    content = (
        "# AWS bootstrap environment\n"
        f"FLEET_REGION={_v('region', 'ap-northeast-1')}\n"
        f"FLEET_SQS_NAME={_v('sqs_name')}\n"
        f"FLEET_STATE_TABLE={_v('state_table')}\n"
        f"FLEET_BUDGET_TABLE={_v('budget_table')}\n"
        f"NAVAL_BUDGET_GUARD_TABLE={_v('budget_guard_table')}\n"
        f"NAVAL_INDEX_TABLE={_v('index_table')}\n"
        f"FLEET_S3_BUCKET={_v('artifact_bucket')}\n"
    )
    env_file.write_text(content, encoding="utf-8")
    return env_file


def bootstrap_aws(
    repo_root: Path,
    *,
    apply: bool,
    region: str,
    name_prefix: str,
) -> AwsBootstrapResult:
    tf_dir, created = ensure_aws_bootstrap_files(repo_root)
    env_file = repo_root / AWS_ENV_FILE
    safe_prefix = _sanitize_name_prefix(name_prefix)
    if not apply:
        return AwsBootstrapResult(
            terraform_dir=tf_dir,
            env_file=env_file,
            created_files=created,
            applied=False,
            message=(
                "terraform scaffold generated. run: "
                f"terraform -chdir={tf_dir} init && "
                f"terraform -chdir={tf_dir} apply -auto-approve "
                f"-var=region={region} -var=name_prefix={safe_prefix}"
            ),
        )

    if shutil.which("terraform") is None:
        return AwsBootstrapResult(
            terraform_dir=tf_dir,
            env_file=env_file,
            created_files=created,
            applied=False,
            message="terraform command not found. install Terraform and run apply manually.",
        )

    init_cmd = ["terraform", "-chdir", str(tf_dir), "init", "-input=false"]
    init_proc = subprocess.run(init_cmd, cwd=str(repo_root))
    if init_proc.returncode != 0:
        return AwsBootstrapResult(
            terraform_dir=tf_dir,
            env_file=env_file,
            created_files=created,
            applied=False,
            message=f"terraform init failed with exit_code={init_proc.returncode}",
        )

    apply_cmd = [
        "terraform",
        "-chdir",
        str(tf_dir),
        "apply",
        "-auto-approve",
        f"-var=region={region}",
        f"-var=name_prefix={safe_prefix}",
    ]
    apply_proc = subprocess.run(apply_cmd, cwd=str(repo_root))
    if apply_proc.returncode != 0:
        return AwsBootstrapResult(
            terraform_dir=tf_dir,
            env_file=env_file,
            created_files=created,
            applied=False,
            message=f"terraform apply failed with exit_code={apply_proc.returncode}",
        )

    outputs = _terraform_output_json(repo_root, tf_dir)
    if outputs:
        written_env = _write_aws_env_file(repo_root, outputs)
        if written_env not in created:
            created.append(written_env)

    return AwsBootstrapResult(
        terraform_dir=tf_dir,
        env_file=env_file,
        created_files=created,
        applied=True,
        message="terraform apply completed",
    )


def bootstrap_local(repo_root: Path, *, apply: bool) -> LocalBootstrapResult:
    compose_file, env_file, created = ensure_local_bootstrap_files(repo_root)
    if not apply:
        msg = (
            "scaffold generated. run: "
            f"docker compose -f {compose_file.name} --env-file {env_file.name} up -d"
        )
        return LocalBootstrapResult(compose_file, env_file, created, False, msg)

    if shutil.which("docker") is None:
        return LocalBootstrapResult(
            compose_file,
            env_file,
            created,
            False,
            "docker command not found. install Docker, then run compose manually.",
        )

    cmd = [
        "docker",
        "compose",
        "-f",
        str(compose_file),
        "--env-file",
        str(env_file),
        "up",
        "-d",
    ]
    proc = subprocess.run(cmd, cwd=str(repo_root))
    if proc.returncode != 0:
        return LocalBootstrapResult(
            compose_file,
            env_file,
            created,
            False,
            f"docker compose failed with exit_code={proc.returncode}",
        )
    return LocalBootstrapResult(compose_file, env_file, created, True, "docker compose started")
